//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatementsImporterLib.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Cashflow
    {
        public tbl_Cashflow()
        {
            this.tbl_CashflowInCashflow = new HashSet<tbl_CashflowInCashflow>();
            this.tbl_CashflowInCashflow1 = new HashSet<tbl_CashflowInCashflow>();
            this.tbl_CashflowRight = new HashSet<tbl_CashflowRight>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedByID { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedByID { get; set; }
        public Nullable<System.Guid> CashAccountID { get; set; }
        public string TypeID { get; set; }
        public Nullable<System.Guid> RecipientID { get; set; }
        public Nullable<System.Guid> PayerID { get; set; }
        public Nullable<System.Guid> ContactID { get; set; }
        public Nullable<System.Guid> OpportunityID { get; set; }
        public Nullable<System.Guid> ContractID { get; set; }
        public Nullable<System.Guid> InvoiceID { get; set; }
        public Nullable<System.Guid> CampaignID { get; set; }
        public Nullable<System.Guid> StatusID { get; set; }
        public Nullable<System.Guid> PeriodID { get; set; }
        public Nullable<System.Guid> CurrencyID { get; set; }
        public Nullable<System.Guid> CategoryID { get; set; }
        public Nullable<System.DateTime> EstimatedDate { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public byte[] Description { get; set; }
        public string Subject { get; set; }
        public Nullable<decimal> CurrencyRate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> BasicAmount { get; set; }
        public Nullable<System.Guid> LinkID { get; set; }
        public Nullable<System.Guid> OwnerID { get; set; }
        public Nullable<System.Guid> ClauseID { get; set; }
        public Nullable<int> UseAsCashflow { get; set; }
        public Nullable<int> UseAsPandL { get; set; }
        public int AutocalcAmount { get; set; }
        public string CFNumber { get; set; }
        public Nullable<System.Guid> ExpenseTypeID { get; set; }
        public Nullable<System.Guid> ProjectID { get; set; }
        public Nullable<System.Guid> IncidentID { get; set; }
        public Nullable<System.Guid> ServiceAgreementID { get; set; }
        public Nullable<System.Guid> DebtorCreditorID { get; set; }
        public Nullable<System.DateTime> ExpactablePayDate { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.Guid> ManagerID { get; set; }
        public int MailSent { get; set; }
        public string Comments { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public string Obj1cDocNumIn { get; set; }
        public string UID1C { get; set; }
    
        public virtual tbl_Account tbl_Account { get; set; }
        public virtual tbl_Account tbl_Account1 { get; set; }
        public virtual tbl_Account tbl_Account2 { get; set; }
        public virtual tbl_CashflowClause tbl_CashflowClause { get; set; }
        public virtual tbl_Contact tbl_Contact { get; set; }
        public virtual tbl_Contract tbl_Contract { get; set; }
        public virtual ICollection<tbl_CashflowInCashflow> tbl_CashflowInCashflow { get; set; }
        public virtual ICollection<tbl_CashflowInCashflow> tbl_CashflowInCashflow1 { get; set; }
        public virtual tbl_Invoice tbl_Invoice { get; set; }
        public virtual tbl_CashflowInCashflow tbl_CashflowInCashflow2 { get; set; }
        public virtual tbl_Contact tbl_Contact1 { get; set; }
        public virtual tbl_Contact tbl_Contact2 { get; set; }
        public virtual tbl_Period tbl_Period { get; set; }
        public virtual ICollection<tbl_CashflowRight> tbl_CashflowRight { get; set; }
    }
}
