//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatementsImporterLib.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Invoice
    {
        public tbl_Invoice()
        {
            this.tbl_Cashflow = new HashSet<tbl_Cashflow>();
        }
    
        public System.Guid ID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<System.Guid> OpportunityID { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.Guid> ContractID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.Guid> SupplierID { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public Nullable<System.Guid> CurrencyID { get; set; }
        public Nullable<decimal> CurrencyRate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> BasicAmount { get; set; }
        public Nullable<System.Guid> CampaignID { get; set; }
        public Nullable<System.Guid> ChannelID { get; set; }
        public Nullable<System.Guid> OwnerID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedByID { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedByID { get; set; }
        public byte[] Description { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<System.Guid> BillStatusID { get; set; }
        public Nullable<System.Guid> ContactID { get; set; }
        public Nullable<System.Guid> WorkflowItemID { get; set; }
        public Nullable<System.Guid> ProjectID { get; set; }
        public Nullable<decimal> BasicPaymentAmount { get; set; }
        public Nullable<System.Guid> ShipmentStateID { get; set; }
        public string Date1C { get; set; }
        public string Object1C { get; set; }
        public string Code1C { get; set; }
        public Nullable<System.Guid> UID1C { get; set; }
        public Nullable<System.DateTime> ExpectablePayDate { get; set; }
        public Nullable<System.Guid> CategoryID { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public Nullable<System.DateTime> PlannedPayDate { get; set; }
        public Nullable<System.Guid> ManagerID { get; set; }
        public string InvoicePayType { get; set; }
        public Nullable<int> DelayDays { get; set; }
        public Nullable<int> Database1CIndex { get; set; }
        public Nullable<int> IsRIPE { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public int MailSent { get; set; }
        public Nullable<System.Guid> TypeID { get; set; }
        public Nullable<System.Guid> LogisticsID { get; set; }
    
        public virtual tbl_Account tbl_Account { get; set; }
        public virtual tbl_Account tbl_Account1 { get; set; }
        public virtual ICollection<tbl_Cashflow> tbl_Cashflow { get; set; }
        public virtual tbl_Contact tbl_Contact { get; set; }
        public virtual tbl_Contact tbl_Contact1 { get; set; }
        public virtual tbl_Contact tbl_Contact2 { get; set; }
        public virtual tbl_Contract tbl_Contract { get; set; }
    }
}
