//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatementsImporterLib.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Contact
    {
        public tbl_Contact()
        {
            this.tbl_Account = new HashSet<tbl_Account>();
            this.tbl_Account1 = new HashSet<tbl_Account>();
            this.tbl_AdminUnit = new HashSet<tbl_AdminUnit>();
            this.tbl_Contact1 = new HashSet<tbl_Contact>();
            this.tbl_Contact11 = new HashSet<tbl_Contact>();
            this.tbl_Invoice = new HashSet<tbl_Invoice>();
            this.tbl_Invoice1 = new HashSet<tbl_Invoice>();
            this.tbl_Invoice2 = new HashSet<tbl_Invoice>();
            this.tbl_Contract = new HashSet<tbl_Contract>();
            this.tbl_Contract1 = new HashSet<tbl_Contract>();
            this.tbl_Contract2 = new HashSet<tbl_Contract>();
            this.tbl_Contract3 = new HashSet<tbl_Contract>();
            this.tbl_Cashflow = new HashSet<tbl_Cashflow>();
            this.tbl_Cashflow1 = new HashSet<tbl_Cashflow>();
            this.tbl_Cashflow2 = new HashSet<tbl_Cashflow>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> AccountID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Name { get; set; }
        public string TimeZone { get; set; }
        public Nullable<System.Guid> CreatedByID { get; set; }
        public Nullable<System.Guid> ModifiedByID { get; set; }
        public string Dear { get; set; }
        public Nullable<System.Guid> SalutationID { get; set; }
        public string GenderID { get; set; }
        public Nullable<System.Guid> DepartmentID { get; set; }
        public Nullable<System.Guid> JobID { get; set; }
        public string JobTitle { get; set; }
        public Nullable<System.Guid> OwnerID { get; set; }
        public string Address { get; set; }
        public Nullable<System.Guid> AddressTypeID { get; set; }
        public Nullable<System.Guid> CityID { get; set; }
        public Nullable<System.Guid> StateID { get; set; }
        public Nullable<System.Guid> CountryID { get; set; }
        public Nullable<System.Guid> TerritoryID { get; set; }
        public string ZIP { get; set; }
        public string Communication1 { get; set; }
        public string Communication2 { get; set; }
        public string Communication3 { get; set; }
        public string Communication4 { get; set; }
        public Nullable<System.Guid> Communication1TypeID { get; set; }
        public Nullable<System.Guid> Communication2TypeID { get; set; }
        public Nullable<System.Guid> Communication3TypeID { get; set; }
        public Nullable<System.Guid> Communication4TypeID { get; set; }
        public Nullable<System.Guid> DecisionRoleID { get; set; }
        public Nullable<System.Guid> CampaignID { get; set; }
        public byte[] Description { get; set; }
        public Nullable<int> DoNotCall { get; set; }
        public Nullable<int> EmailOptOut { get; set; }
        public Nullable<System.Guid> ContactTypeID { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> PTS2010 { get; set; }
        public Nullable<int> PTS2010Seminar { get; set; }
        public string Object1C { get; set; }
        public string Code1C { get; set; }
        public Nullable<System.Guid> AssistantID { get; set; }
        public Nullable<System.Guid> EmployeeStateID { get; set; }
        public Nullable<int> InternalNumber { get; set; }
    
        public virtual ICollection<tbl_Account> tbl_Account { get; set; }
        public virtual ICollection<tbl_Account> tbl_Account1 { get; set; }
        public virtual tbl_Account tbl_Account2 { get; set; }
        public virtual ICollection<tbl_AdminUnit> tbl_AdminUnit { get; set; }
        public virtual ICollection<tbl_Contact> tbl_Contact1 { get; set; }
        public virtual tbl_Contact tbl_Contact2 { get; set; }
        public virtual ICollection<tbl_Contact> tbl_Contact11 { get; set; }
        public virtual tbl_Contact tbl_Contact3 { get; set; }
        public virtual ICollection<tbl_Invoice> tbl_Invoice { get; set; }
        public virtual ICollection<tbl_Invoice> tbl_Invoice1 { get; set; }
        public virtual ICollection<tbl_Invoice> tbl_Invoice2 { get; set; }
        public virtual ICollection<tbl_Contract> tbl_Contract { get; set; }
        public virtual ICollection<tbl_Contract> tbl_Contract1 { get; set; }
        public virtual ICollection<tbl_Contract> tbl_Contract2 { get; set; }
        public virtual ICollection<tbl_Contract> tbl_Contract3 { get; set; }
        public virtual ICollection<tbl_Cashflow> tbl_Cashflow { get; set; }
        public virtual ICollection<tbl_Cashflow> tbl_Cashflow1 { get; set; }
        public virtual ICollection<tbl_Cashflow> tbl_Cashflow2 { get; set; }
    }
}
