//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatementsImporterLib.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CashflowInCashflow
    {
        public tbl_CashflowInCashflow()
        {
            this.tbl_Cashflow2 = new HashSet<tbl_Cashflow>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedByID { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedByID { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public Nullable<System.Guid> ChildID { get; set; }
    
        public virtual tbl_Cashflow tbl_Cashflow { get; set; }
        public virtual tbl_Cashflow tbl_Cashflow1 { get; set; }
        public virtual ICollection<tbl_Cashflow> tbl_Cashflow2 { get; set; }
    }
}
