//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatementsImporterLib.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CashflowRight
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> RecordID { get; set; }
        public Nullable<System.Guid> AdminUnitID { get; set; }
        public Nullable<int> CanRead { get; set; }
        public Nullable<int> CanWrite { get; set; }
        public Nullable<int> CanDelete { get; set; }
        public Nullable<int> CanChangeAccess { get; set; }
    
        public virtual tbl_AdminUnit tbl_AdminUnit { get; set; }
        public virtual tbl_Cashflow tbl_Cashflow { get; set; }
    }
}
